# **Ejercicio #4 Aplique a su dataset el etiquetado simple y binario.**




Como mi dataset no tiene columnas con datos cualitativos aplicaremos el etiquetados a nombres de ciudades

# **Etiquetado simple**

In [5]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder


datos=['Paris', 'Londres', 'Nueva York', 'Roma', 'Tokio', 'Madrid', 'Berlín', 'Sídney', 'Pekín', 'Toronto','Roma']
metodo=LabelEncoder()
datos2=metodo.fit_transform(datos)
#mostramos las clases unicas encontradas
print("Clases unicas encontradas: ",metodo.classes_)
print("Datos con etiquetado simple: ",datos2)
datos1=metodo.inverse_transform(datos2)
print("Datos iniciales trqansformación inversa: ",datos1)

Clases unicas encontradas:  ['Berlín' 'Londres' 'Madrid' 'Nueva York' 'Paris' 'Pekín' 'Roma' 'Sídney'
 'Tokio' 'Toronto']
Datos con etiquetado simple:  [4 1 3 6 8 2 0 7 5 9 6]
Datos iniciales trqansformación inversa:  ['Paris' 'Londres' 'Nueva York' 'Roma' 'Tokio' 'Madrid' 'Berlín' 'Sídney'
 'Pekín' 'Toronto' 'Roma']


# **Etiquetado binario**

In [7]:
import numpy as np
#datos en 2d
datos2 = np.array(datos).reshape(-1, 1)
metodo=OneHotEncoder()
metodo.fit(datos2)

datos3=metodo.transform(datos2)
print("Clases unicas encontradas: ",metodo.categories_)
print("Datos codificados: ",datos3.toarray())
datos_decodificados = metodo.inverse_transform(datos3)
print("Datos decodificados: ",datos_decodificados)


Clases unicas encontradas:  [array(['Berlín', 'Londres', 'Madrid', 'Nueva York', 'Paris', 'Pekín',
       'Roma', 'Sídney', 'Tokio', 'Toronto'], dtype='<U10')]
Datos codificados:  [[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]
Datos decodificados:  [['Paris']
 ['Londres']
 ['Nueva York']
 ['Roma']
 ['Tokio']
 ['Madrid']
 ['Berlín']
 ['Sídney']
 ['Pekín']
 ['Toronto']
 ['Roma']]
